### ISSUE TITLE
Not compatible with serverless-dotenv-plugin

### ISSUE THREAD

**Issue by ronaldborla** [KrysKruk/serverless-import-config-plugin#1]
For some reason, the imported file is not compatible with this plugin: https://github.com/colynb/serverless-dotenv-plugin

It does not use environment variables.

The plugin looks promising, I would like to contribute but I'm a bit occupied at the moment. I hope you can check this out. Thanks!

**Comment by KrysKruk** [comment]
Hi @ronaldborla.

I use `serverless-dotenv-plugin` together with this plugin in my projects and it works fine for me.
I wanted to be sure so I checked it on a fresh config and still, no issues.

Do you see any errors or can you provide more informations what exactly doesn't work for you?
Do you see `Serverless: DOTENV: Loading environment variables from .env:` log when packaging your serverless project? 

So I created a `imported.yml` file with a content:
```yaml
functions:
  func1:
    handler: ${env:TEST_FUNC1}.handler
  func2:
    handler: ${env:TEST_FUNC2}.handler
```

In the main `serverles.yml` file I placed:
```yaml
service: test1
plugins:
  - serverless-import-config-plugin
  - serverless-dotenv-plugin
custom:
  import:
    - ./imported.yml
provider:
  name: aws
package:
  individually: true
```

... and I had no issues with using env variables from the `.env` file.

Please let me know how I can help here. Thanks.
