### ISSUE TITLE
Overwriting imported values

### ISSUE THREAD

**Issue by PatrykMilewski** [KrysKruk/serverless-import-config-plugin#2]
Hey!

I was testing this plugin and it works great, but I found one use case, that is not supported.

I would like to import common base serverless.yml file in each stack and in some cases, I may want to overwrite some of the imported keys values. Example:
`/serverless.yml`
```
provider:
  aws: aws
  runtime: nodejs10.x
  memory: 128
```

`/childStack/serverless.yml`
```
custom:
  import: ../serverless.yml

provider:
  memory: 256
```

Is this possible to achieve this using this plugin?

**Comment by KrysKruk** [comment]
Hi @PatrykMilewski !

All already existing parameters will not be overwritten, so your example should work just fine and the final config would be:

```yaml
provider:
  aws: aws
  runtime: nodejs10.x
  memory: 256
```

Let me know if that works for you. If not, that would be a bug.

I guess README should be more precise, sorry for that.

**Comment by PatrykMilewski** [comment]
Thank you for response @KrysKruk

I can't get it to work, there is another example with outputs:

`/tmp/serverless.yml`
```
provider:
  name: aws
  stackName: ${self:custom.baseName}
  runtime: nodejs12.x
  memory: 128
```

`/tmp/child/serverless.yml`
```
service: example-service

plugins:
  - serverless-import-config-plugin

custom:
  baseName: baseName-example
  import: ../serverless.yml

provider:
  memorySize: 256
```

Then trying to check, if it works:
```
cd /tmp/child/
sls print
```
It outputs:
```
Serverless: Importing ../serverless.yml
service: example-service
plugins:
  - serverless-import-config-plugin
custom:
  baseName: baseName-example
  import: ../serverless.yml
provider:
  memorySize: 256
```

Is this expected or I'm doing something wrong?
