### ISSUE TITLE
Incorrect path to handler generated on win32 platform

### ISSUE THREAD

**Issue by tkurylek** [KrysKruk/serverless-import-config-plugin#5]
Hello.
First of all thanks a lot for this plugin. I discovered a small issue which affects Windows platform.

On Windows platform the generated path to handler:
```yml
functions:
  myfeature-myaction:
    handler: actions/myaction/handler.handler
```
includes Windows path separator (`\`) instead of posix separator (`/`). This results in an error on AWS Lambda.
<img width="1030" alt="Screenshot 2020-08-25 at 9 11 10 AM" src="https://user-images.githubusercontent.com/1387716/91143507-ec39ce80-e6b2-11ea-9db1-990f84a4da2c.png">

Could you kindly accept my PR with the proposed fix and publish a new version to npm repository?
